### PR TITLE
SPMP Version 0.3

### PR DESCRIPTION
**Pull request by DancingEmus**
1. Addition of members to Role And Responsibilities **(4.2)**
2. Addition Group Representatives **(4.3)** 
3. Addition of  Standards **(4.4)**
4. Reorder by alphabetical of Roles and Responsibilities **(4.2)**
5. Grammatical editing **(5.1)** 

_Authors :_ @AliShahidGit,  @danhuynh1, @Jamie-Omorodion, @kobilee, @pint5070  @NickMarecek, @prayritkhanna

### CODE REVIEW

**Review by JoshuaVarga — APPROVED** [review]

**Review by NickMarecek — APPROVED** [review]

**Comment by JoshuaVarga** [comment]
Go ahead and merge\delete the branch.

**Comment by DancingEmus** [comment]
> Go ahead and merge\delete the branch.

For me it says that I'm not authorized to merge this pull request.

**Comment by JoshuaVarga** [comment]
I changed some settings let me know if it works now.

**Comment by DancingEmus** [comment]
> I changed some settings let me know if it works now.

Not yet, this is still what I see
screen shot 2018-10-15 at 3 36 08 pm

**Comment by JoshuaVarga** [comment]
Fixed it lol.

**Comment by DancingEmus** [comment]
> Fixed it lol.

Lol thanks man

**Pull request merged**
